export const tickCommonNames = [
  "American Dog Tick",
  "Asian Longhorned Tick",
  "Asiatic Cattle Tick",
  "Australian Paralysis Tick",
  "Bighorn Sheep Tick",
  "Blyborough Tick",
  "Bont Ticks",
  "Brown Dog Tick",
  "Brown Ear Tick",
  "Camel Tick",
  "Castor Bean Tick",
  "Cayenne Tick",
  "Dog Ticks",
  "Eastern Black-legged Tick",
  "Fowl Tick",
  "Groundhog Tick",
  "Gulf Coast Tick",
  "Kangaroo Tick",
  "Lone Star Tick",
  "Ornate Cow Tick",
  "Ornate Sheep Tick",
  "Pacific Coast Tick",
  "Pajahuello Tick",
  "Passerine Tick",
  "Pepper Ticks",
  "Pigeon Tick",
  "Rabbit Tick",
  "Rhinoceros Tick",
  "Rocky Mountain Wood Tick",
  "Sand Tampan",
  "Seabird Tick",
  "South African Bont Tick",
  "Southern Reptile Tick",
  "Tasmanian Paralysis Tick",
  "Tortoise Bont Tick",
  "Tortoise Tick",
  "Tropical Bont Tick",
  "Tuatara Tick",
  "Western Black-legged Tick",
  "Western Dog Tick",
  "Winter Tick",
  "Zebra Tick",
  "Bush Tick",
  "Gopher Tortoise Tick",
  "Hedgehog Tick",
  "Long-legged Bat Tick",
  "Red Sheep Tick",
  "Taiga Tick"
];

export const tickScientificNames = [
  "Amblyomma",
  "Amblyomma albolimbatum",
  "Amblyomma americanum",
  "Amblyomma aureolatum",
  "Amblyomma cajennense",
  "Amblyomma coelebs",
  "Amblyomma cohaerens",
  "Amblyomma cordiferum",
  "Amblyomma dissimile",
  "Amblyomma dubitatum",
  "Amblyomma geoemydae",
  "Amblyomma gervaisi",
  "Amblyomma hebraeum",
  "Amblyomma humerale",
  "Amblyomma incisum",
  "Amblyomma integrum",
  "Amblyomma laticaudae",
  "Amblyomma loculosum",
  "Amblyomma longirostre",
  "Amblyomma maculatum",
  "Amblyomma marmoreum",
  "Amblyomma ovale",
  "Amblyomma rotundatum",
  "Amblyomma sabanerae",
  "Amblyomma scalpturatum",
  "Amblyomma splendidum",
  "Amblyomma sylvaticum",
  "Amblyomma testudinarium",
  "Amblyomma tigrinum",
  "Amblyomma triguttatum",
  "Amblyomma tuberculatum",
  "Amblyomma varanense",
  "Amblyomma variegatum",
  "Archaeocroton sphenodonti",
  "Argas persicus",
  "Argas reflexus",
  "Argas vespertilionis",
  "Bothriocroton hydrosauri",
  "Carios kelleyi",
  "Dermacentor",
  "Dermacentor albipictus",
  "Dermacentor andersoni",
  "Dermacentor auratus",
  "Dermacentor compactus",
  "Dermacentor hunteri",
  "Dermacentor marginatus",
  "Dermacentor occidentalis",
  "Dermacentor reticulatus",
  "Dermacentor rhinocerinus",
  "Dermacentor similis",
  "Dermacentor variabilis",
  "Haemaphysalis bancrofti",
  "Haemaphysalis concinna",
  "Haemaphysalis inermis",
  "Haemaphysalis leporispalustris",
  "Haemaphysalis longicornis",
  "Haemaphysalis punctata",
  "Haemaphysalis semermis",
  "Haemaphysalis sulcata",
  "Hyalomma",
  "Hyalomma aegyptium",
  "Hyalomma dromedarii",
  "Hyalomma marginatum",
  "Ixodes",
  "Ixodes acutitarsus",
  "Ixodes cookei",
  "Ixodes cornuatus",
  "Ixodes frontalis",
  "Ixodes hexagonus",
  "Ixodes hirsti",
  "Ixodes holocyclus",
  "Ixodes ovatus",
  "Ixodes pacificus",
  "Ixodes persulcatus",
  "Ixodes pilosus",
  "Ixodes ricinus",
  "Ixodes scapularis",
  "Ixodes uriae",
  "Ixodes vespertilionis",
  "Ornithodoros coriaceus",
  "Ornithodoros savignyi",
  "Rhipicephalus",
  "Rhipicephalus appendiculatus",
  "Rhipicephalus bursa",
  "Rhipicephalus evertsi",
  "Rhipicephalus maculatus",
  "Rhipicephalus microplus",
  "Rhipicephalus pulchellus",
  "Rhipicephalus sanguineus",
  "Robertsicus elaphensis"

];


export const yearlyLymeDiseaseByCountyTilesetIds: {[year: string]: {url: string, "source-layer": string} }= {
  "2000": {"url": "mapbox://rsultan.87mce39g", "source-layer": "lymeDiseaseByUSCounty2000-2noola"},
  "2001": {"url": "mapbox://rsultan.87da5wz7", "source-layer": "lymeDiseaseByUSCounty2001-26ffxj"},
  "2002": {"url": "mapbox://rsultan.34r86yl7", "source-layer": "lymeDiseaseByUSCounty2002-4mp4o6"},
  "2003": {"url": "mapbox://rsultan.bsjdehjw", "source-layer": "lymeDiseaseByUSCounty2003-54l2ta"},
  "2004": {"url": "mapbox://rsultan.0xukrp5s", "source-layer": "lymeDiseaseByUSCounty2004-adbx4d"},
  "2005": {"url": "mapbox://rsultan.7z1dfnd1", "source-layer": "lymeDiseaseByUSCounty2005-3ygahm"},
  "2006": {"url": "mapbox://rsultan.60124944", "source-layer": "lymeDiseaseByUSCounty2006-6v4abv"},
  "2007": {"url": "mapbox://rsultan.18il9cvt", "source-layer": "lymeDiseaseByUSCounty2007-d9vt3e"},
  "2008": {"url": "mapbox://rsultan.10i7jnkp", "source-layer": "lymeDiseaseByUSCounty2008-0lb1q8"},
  "2009": {"url": "mapbox://rsultan.6dwzpj1l", "source-layer": "lymeDiseaseByUSCounty2009-9iovq7"},
  "2010": {"url": "mapbox://rsultan.80ohdj00", "source-layer": "lymeDiseaseByUSCounty2010-9q71z8"},
  "2011": {"url": "mapbox://rsultan.2kgc2o75", "source-layer": "lymeDiseaseByUSCounty2011-4hwt5q"},
  "2012": {"url": "mapbox://rsultan.9pnuy3rq", "source-layer": "lymeDiseaseByUSCounty2012-cd8cog"},
  "2013": {"url": "mapbox://rsultan.cihe7ks2", "source-layer": "lymeDiseaseByUSCounty2013-0yae86"},
  "2014": {"url": "mapbox://rsultan.au26pjq8", "source-layer": "lymeDiseaseByUSCounty2014-8mitri"},
  "2015": {"url": "mapbox://rsultan.774i0mf0", "source-layer": "lymeDiseaseByUSCounty2015-9ljyzs"},
  "2016": {"url": "mapbox://rsultan.4s7cz2nq", "source-layer": "lymeDiseaseByUSCounty2016-ctys5r"},
  "2017": {"url": "mapbox://rsultan.dhcenvrl", "source-layer": "lymeDiseaseByUSCounty2017-803ny6"},
  "2018": {"url": "mapbox://rsultan.dsxl6dxq",  "source-layer": "lymeDiseaseByUSCounty2018-45ec41"},
  "2019": {"url": "mapbox://rsultan.bxsn6ya7",  "source-layer": "lymeDiseaseByUSCounty2019-cjpxa0"}
};

export const tickNamesTrivia = [
  "American Dog Tick",
  "Ornate Sheep Tick",
  "Eastern Black-legged Tick",
  "Pacific Coast Tick",
  "Lone Star Tick",
  "Castor Bean Tick",
  "Western Dog Tick",
  "Southern Reptile Tick",
  "Ornate Cow Tick",
  "Western Black-legged Tick",
  "Gulf Coast Tick",
  "Zebra tick",
  "Australian Paralysis Tick",
  "Rhinoceros Tick",
  "South African Bont Tick",
  "Brown Dog Tick",
  "taiga tick",
  "Bighorn Sheep Tick",
  "Tuatara tick",
  "long-legged bat tick",
  "Tasmanian Paralysis Tick",
  "gopher tortoise tick",
  "Winter tick",
  "Tortoise tick",
  "Kangaroo Tick",
  "red sheep tick",
  "Rocky Mountain Wood Tick",
  "Tropical Bont Tick",
  "Cayenne Tick",
  "Tortoise Bont Tick",
  "Passerine Tick",
  //"Dog Ticks",
  "Sand Tampan",
  "Blyborough tick",
  "Bont Ticks",
  "Pigeon Tick",
  "Rabbit Tick",
  "Pajahuello Tick",
  "Asiatic Cattle Tick",
  "Seabird Tick",
  "Asian Longhorned Tick",
  "hedgehog tick",
  "bush tick",
  "Pepper Ticks",
  "Fowl Tick",
  "Camel Tick",
  "Brown Ear Tick",
  "Groundhog Tick"
];

export const tickDiseases = {
  "American Dog Tick": "Rocky Mountain spotted fever, tularemia",
  "Ornate Sheep Tick": "Q fever",
  "Eastern Black-legged Tick": "Lyme disease, anaplasmosis, babesiosis, Powassan virus",
  "Pacific Coast Tick": "Rickettsiosis",
  "Lone Star Tick": "Ehrlichiosis, tularemia, STARI",
  "Castor Bean Tick": "Q fever",
  "Western Dog Tick": "Rocky Mountain spotted fever, tularemia",
  "Southern Reptile Tick": "Rickettsiosis",
  "Ornate Cow Tick": "Anaplasmosis",
  "Western Black-legged Tick": "Lyme disease, anaplasmosis, babesiosis",
  "Gulf Coast Tick": "Rickettsiosis",
  "Zebra tick": "Heartwater disease",
  "Australian Paralysis Tick": "Tick paralysis",
  "Rhinoceros Tick": "Anaplasmosis",
  "South African Bont Tick": "Heartwater disease",
  "Brown Dog Tick": "Ehrlichiosis, Rocky Mountain spotted fever",
  "taiga tick": "Lyme disease",
  "Bighorn Sheep Tick": "Anaplasmosis",
  "Tuatara tick": "Q fever",
  "long-legged bat tick": "Rabies",
  "Tasmanian Paralysis Tick": "Tick paralysis",
  "gopher tortoise tick": "Rickettsiosis",
  "Winter tick": "Anaplasmosis, Lyme disease",
  "Tortoise tick": "Rickettsiosis",
  "Kangaroo Tick": "Q fever",
  "red sheep tick": "Heartwater disease",
  "Rocky Mountain Wood Tick": "Rocky Mountain spotted fever, Colorado tick fever, tularemia",
  "Tropical Bont Tick": "Heartwater disease",
  "Cayenne Tick": "Heartwater disease",
  "Tortoise Bont Tick": "Heartwater disease",
  "Passerine Tick": "Borrelia turicatae",
  "Sand Tampan": "Tick bite fever",
  "Blyborough tick": "Borrelia lonestari",
  "Bont Ticks": "Heartwater disease",
  "Pigeon Tick": "",
  "Rabbit Tick": "Tularaemia",
  "Pajahuello Tick": "Tick paralysis",
  "Asiatic Cattle Tick": "Babesiosis, anaplasmosis",
  "Seabird Tick": "Borrelia garinii",
  "Asian Longhorned Tick": "Rickettsiosis, Powassan virus",
  "hedgehog tick": "Lyme disease",
  "bush tick": "Queensland tick typhus",
  "Pepper Ticks": "Q fever",
  "Fowl Tick": "avian spirochetosis",
  "Camel Tick": "Crimean-Congo hemorrhagic fever",
  "Brown Ear Tick": "Theileriosis",
  "Groundhog Tick": "Rocky Mountain spotted fever"
};


export const wikiPageIds = {
  "Amblyomma americanum": "Amblyomma_americanum",
  "Amblyomma maculatum": "Amblyomma_maculatum",
  "Dermacentor andersoni": "Dermacentor_andersoni",
  "Dermacentor marginatus": "Dermacentor_marginatus",
  "Dermacentor occidentalis": "Dermacentor_occidentalis",
  "Dermacentor reticulatus": "Dermacentor_reticulatus",
  "Dermacentor variabilis": "Dermacentor_variabilis",
  "Ixodes pacificus": "Ixodes_pacificus",
  "Ixodes ricinus": "Ixodes_ricinus",
  "Ixodes scapularis": "Ixodes_scapularis",
  "Rhipicephalus sanguineus": "Rhipicephalus_sanguineus"

}

export const classLabels = ["tench",
  "goldfish",
  "great white shark",
  "tiger shark",
  "hammerhead shark",
  "electric ray",
  "stingray",
  "cock",
  "hen",
  "ostrich",
  "brambling",
  "goldfinch",
  "house finch",
  "junco",
  "indigo bunting",
  "American robin",
  "bulbul",
  "jay",
  "magpie",
  "chickadee",
  "American dipper",
  "kite",
  "bald eagle",
  "vulture",
  "great grey owl",
  "fire salamander",
  "smooth newt",
  "newt",
  "spotted salamander",
  "axolotl",
  "American bullfrog",
  "tree frog",
  "tailed frog",
  "loggerhead sea turtle",
  "leatherback sea turtle",
  "mud turtle",
  "terrapin",
  "box turtle",
  "banded gecko",
  "green iguana",
  "Carolina anole",
  "desert grassland whiptail lizard",
  "agama",
  "frilled-necked lizard",
  "alligator lizard",
  "Gila monster",
  "European green lizard",
  "chameleon",
  "Komodo dragon",
  "Nile crocodile",
  "American alligator",
  "triceratops",
  "worm snake",
  "ring-necked snake",
  "eastern hog-nosed snake",
  "smooth green snake",
  "kingsnake",
  "garter snake",
  "water snake",
  "vine snake",
  "night snake",
  "boa constrictor",
  "African rock python",
  "Indian cobra",
  "green mamba",
  "sea snake",
  "Saharan horned viper",
  "eastern diamondback rattlesnake",
  "sidewinder",
  "trilobite",
  "harvestman",
  "scorpion",
  "yellow garden spider",
  "barn spider",
  "European garden spider",
  "southern black widow",
  "tarantula",
  "wolf spider",
  "tick",
  "centipede",
  "black grouse",
  "ptarmigan",
  "ruffed grouse",
  "prairie grouse",
  "peacock",
  "quail",
  "partridge",
  "grey parrot",
  "macaw",
  "sulphur-crested cockatoo",
  "lorikeet",
  "coucal",
  "bee eater",
  "hornbill",
  "hummingbird",
  "jacamar",
  "toucan",
  "duck",
  "red-breasted merganser",
  "goose",
  "black swan",
  "tusker",
  "echidna",
  "platypus",
  "wallaby",
  "koala",
  "wombat",
  "jellyfish",
  "sea anemone",
  "brain coral",
  "flatworm",
  "nematode",
  "conch",
  "snail",
  "slug",
  "sea slug",
  "chiton",
  "chambered nautilus",
  "Dungeness crab",
  "rock crab",
  "fiddler crab",
  "red king crab",
  "American lobster",
  "spiny lobster",
  "crayfish",
  "hermit crab",
  "isopod",
  "white stork",
  "black stork",
  "spoonbill",
  "flamingo",
  "little blue heron",
  "great egret",
  "bittern",
  "crane (bird)",
  "limpkin",
  "common gallinule",
  "American coot",
  "bustard",
  "ruddy turnstone",
  "dunlin",
  "common redshank",
  "dowitcher",
  "oystercatcher",
  "pelican",
  "king penguin",
  "albatross",
  "grey whale",
  "killer whale",
  "dugong",
  "sea lion",
  "Chihuahua",
  "Japanese Chin",
  "Maltese",
  "Pekingese",
  "Shih Tzu",
  "King Charles Spaniel",
  "Papillon",
  "toy terrier",
  "Rhodesian Ridgeback",
  "Afghan Hound",
  "Basset Hound",
  "Beagle",
  "Bloodhound",
  "Bluetick Coonhound",
  "Black and Tan Coonhound",
  "Treeing Walker Coonhound",
  "English foxhound",
  "Redbone Coonhound",
  "borzoi",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Whippet",
  "Ibizan Hound",
  "Norwegian Elkhound",
  "Otterhound",
  "Saluki",
  "Scottish Deerhound",
  "Weimaraner",
  "Staffordshire Bull Terrier",
  "American Staffordshire Terrier",
  "Bedlington Terrier",
  "Border Terrier",
  "Kerry Blue Terrier",
  "Irish Terrier",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Yorkshire Terrier",
  "Wire Fox Terrier",
  "Lakeland Terrier",
  "Sealyham Terrier",
  "Airedale Terrier",
  "Cairn Terrier",
  "Australian Terrier",
  "Dandie Dinmont Terrier",
  "Boston Terrier",
  "Miniature Schnauzer",
  "Giant Schnauzer",
  "Standard Schnauzer",
  "Scottish Terrier",
  "Tibetan Terrier",
  "Australian Silky Terrier",
  "Soft-coated Wheaten Terrier",
  "West Highland White Terrier",
  "Lhasa Apso",
  "Flat-Coated Retriever",
  "Curly-coated Retriever",
  "Golden Retriever",
  "Labrador Retriever",
  "Chesapeake Bay Retriever",
  "German Shorthaired Pointer",
  "Vizsla",
  "English Setter",
  "Irish Setter",
  "Gordon Setter",
  "Brittany",
  "Clumber Spaniel",
  "English Springer Spaniel",
  "Welsh Springer Spaniel",
  "Cocker Spaniels",
  "Sussex Spaniel",
  "Irish Water Spaniel",
  "Kuvasz",
  "Schipperke",
  "Groenendael",
  "Malinois",
  "Briard",
  "Australian Kelpie",
  "Komondor",
  "Old English Sheepdog",
  "Shetland Sheepdog",
  "collie",
  "Border Collie",
  "Bouvier des Flandres",
  "Rottweiler",
  "German Shepherd Dog",
  "Dobermann",
  "Miniature Pinscher",
  "Greater Swiss Mountain Dog",
  "Bernese Mountain Dog",
  "Appenzeller Sennenhund",
  "Entlebucher Sennenhund",
  "Boxer",
  "Bullmastiff",
  "Tibetan Mastiff",
  "French Bulldog",
  "Great Dane",
  "St. Bernard",
  "husky",
  "Alaskan Malamute",
  "Siberian Husky",
  "Dalmatian",
  "Affenpinscher",
  "Basenji",
  "pug",
  "Leonberger",
  "Newfoundland",
  "Pyrenean Mountain Dog",
  "Samoyed",
  "Pomeranian",
  "Chow Chow",
  "Keeshond",
  "Griffon Bruxellois",
  "Pembroke Welsh Corgi",
  "Cardigan Welsh Corgi",
  "Toy Poodle",
  "Miniature Poodle",
  "Standard Poodle",
  "Mexican hairless dog",
  "grey wolf",
  "Alaskan tundra wolf",
  "red wolf",
  "coyote",
  "dingo",
  "dhole",
  "African wild dog",
  "hyena",
  "red fox",
  "kit fox",
  "Arctic fox",
  "grey fox",
  "tabby cat",
  "tiger cat",
  "Persian cat",
  "Siamese cat",
  "Egyptian Mau",
  "cougar",
  "lynx",
  "leopard",
  "snow leopard",
  "jaguar",
  "lion",
  "tiger",
  "cheetah",
  "brown bear",
  "American black bear",
  "polar bear",
  "sloth bear",
  "mongoose",
  "meerkat",
  "tiger beetle",
  "ladybug",
  "ground beetle",
  "longhorn beetle",
  "leaf beetle",
  "dung beetle",
  "rhinoceros beetle",
  "weevil",
  "fly",
  "bee",
  "ant",
  "grasshopper",
  "cricket",
  "stick insect",
  "cockroach",
  "mantis",
  "cicada",
  "leafhopper",
  "lacewing",
  "dragonfly",
  "damselfly",
  "red admiral",
  "ringlet",
  "monarch butterfly",
  "small white",
  "sulphur butterfly",
  "gossamer-winged butterfly",
  "starfish",
  "sea urchin",
  "sea cucumber",
  "cottontail rabbit",
  "hare",
  "Angora rabbit",
  "hamster",
  "porcupine",
  "fox squirrel",
  "marmot",
  "beaver",
  "guinea pig",
  "common sorrel",
  "zebra",
  "pig",
  "wild boar",
  "warthog",
  "hippopotamus",
  "ox",
  "water buffalo",
  "bison",
  "ram",
  "bighorn sheep",
  "Alpine ibex",
  "hartebeest",
  "impala",
  "gazelle",
  "dromedary",
  "llama",
  "weasel",
  "mink",
  "European polecat",
  "black-footed ferret",
  "otter",
  "skunk",
  "badger",
  "armadillo",
  "three-toed sloth",
  "orangutan",
  "gorilla",
  "chimpanzee",
  "gibbon",
  "siamang",
  "guenon",
  "patas monkey",
  "baboon",
  "macaque",
  "langur",
  "black-and-white colobus",
  "proboscis monkey",
  "marmoset",
  "white-headed capuchin",
  "howler monkey",
  "titi",
  "Geoffroy's spider monkey",
  "common squirrel monkey",
  "ring-tailed lemur",
  "indri",
  "Asian elephant",
  "African bush elephant",
  "red panda",
  "giant panda",
  "snoek",
  "eel",
  "coho salmon",
  "rock beauty",
  "clownfish",
  "sturgeon",
  "garfish",
  "lionfish",
  "pufferfish",
  "abacus",
  "abaya",
  "academic gown",
  "accordion",
  "acoustic guitar",
  "aircraft carrier",
  "airliner",
  "airship",
  "altar",
  "ambulance",
  "amphibious vehicle",
  "analog clock",
  "apiary",
  "apron",
  "waste container",
  "assault rifle",
  "backpack",
  "bakery",
  "balance beam",
  "balloon",
  "ballpoint pen",
  "Band-Aid",
  "banjo",
  "baluster",
  "barbell",
  "barber chair",
  "barbershop",
  "barn",
  "barometer",
  "barrel",
  "wheelbarrow",
  "baseball",
  "basketball",
  "bassinet",
  "bassoon",
  "swimming cap",
  "bath towel",
  "bathtub",
  "station wagon",
  "lighthouse",
  "beaker",
  "military cap",
  "beer bottle",
  "beer glass",
  "bell-cot",
  "bib",
  "tandem bicycle",
  "bikini",
  "ring binder",
  "binoculars",
  "birdhouse",
  "boathouse",
  "bobsleigh",
  "bolo tie",
  "poke bonnet",
  "bookcase",
  "bookstore",
  "bottle cap",
  "bow",
  "bow tie",
  "brass",
  "bra",
  "breakwater",
  "breastplate",
  "broom",
  "bucket",
  "buckle",
  "bulletproof vest",
  "high-speed train",
  "butcher shop",
  "taxicab",
  "cauldron",
  "candle",
  "cannon",
  "canoe",
  "can opener",
  "cardigan",
  "car mirror",
  "carousel",
  "tool kit",
  "carton",
  "car wheel",
  "automated teller machine",
  "cassette",
  "cassette player",
  "castle",
  "catamaran",
  "CD player",
  "cello",
  "mobile phone",
  "chain",
  "chain-link fence",
  "chain mail",
  "chainsaw",
  "chest",
  "chiffonier",
  "chime",
  "china cabinet",
  "Christmas stocking",
  "church",
  "movie theater",
  "cleaver",
  "cliff dwelling",
  "cloak",
  "clogs",
  "cocktail shaker",
  "coffee mug",
  "coffeemaker",
  "coil",
  "combination lock",
  "computer keyboard",
  "confectionery store",
  "container ship",
  "convertible",
  "corkscrew",
  "cornet",
  "cowboy boot",
  "cowboy hat",
  "cradle",
  "crane (machine)",
  "crash helmet",
  "crate",
  "infant bed",
  "Crock Pot",
  "croquet ball",
  "crutch",
  "cuirass",
  "dam",
  "desk",
  "desktop computer",
  "rotary dial telephone",
  "diaper",
  "digital clock",
  "digital watch",
  "dining table",
  "dishcloth",
  "dishwasher",
  "disc brake",
  "dock",
  "dog sled",
  "dome",
  "doormat",
  "drilling rig",
  "drum",
  "drumstick",
  "dumbbell",
  "Dutch oven",
  "electric fan",
  "electric guitar",
  "electric locomotive",
  "entertainment center",
  "envelope",
  "espresso machine",
  "face powder",
  "feather boa",
  "filing cabinet",
  "fireboat",
  "fire engine",
  "fire screen sheet",
  "flagpole",
  "flute",
  "folding chair",
  "football helmet",
  "forklift",
  "fountain",
  "fountain pen",
  "four-poster bed",
  "freight car",
  "French horn",
  "frying pan",
  "fur coat",
  "garbage truck",
  "gas mask",
  "gas pump",
  "goblet",
  "go-kart",
  "golf ball",
  "golf cart",
  "gondola",
  "gong",
  "gown",
  "grand piano",
  "greenhouse",
  "grille",
  "grocery store",
  "guillotine",
  "barrette",
  "hair spray",
  "half-track",
  "hammer",
  "hamper",
  "hair dryer",
  "hand-held computer",
  "handkerchief",
  "hard disk drive",
  "harmonica",
  "harp",
  "harvester",
  "hatchet",
  "holster",
  "home theater",
  "honeycomb",
  "hook",
  "hoop skirt",
  "horizontal bar",
  "horse-drawn vehicle",
  "hourglass",
  "iPod",
  "clothes iron",
  "jack-o'-lantern",
  "jeans",
  "jeep",
  "T-shirt",
  "jigsaw puzzle",
  "pulled rickshaw",
  "joystick",
  "kimono",
  "knee pad",
  "knot",
  "lab coat",
  "ladle",
  "lampshade",
  "laptop computer",
  "lawn mower",
  "lens cap",
  "paper knife",
  "library",
  "lifeboat",
  "lighter",
  "limousine",
  "ocean liner",
  "lipstick",
  "slip-on shoe",
  "lotion",
  "speaker",
  "loupe",
  "sawmill",
  "magnetic compass",
  "mail bag",
  "mailbox",
  "tights",
  "tank suit",
  "manhole cover",
  "maraca",
  "marimba",
  "mask",
  "match",
  "maypole",
  "maze",
  "measuring cup",
  "medicine chest",
  "megalith",
  "microphone",
  "microwave oven",
  "military uniform",
  "milk can",
  "minibus",
  "miniskirt",
  "minivan",
  "missile",
  "mitten",
  "mixing bowl",
  "mobile home",
  "Model T",
  "modem",
  "monastery",
  "monitor",
  "moped",
  "mortar",
  "square academic cap",
  "mosque",
  "mosquito net",
  "scooter",
  "mountain bike",
  "tent",
  "computer mouse",
  "mousetrap",
  "moving van",
  "muzzle",
  "nail",
  "neck brace",
  "necklace",
  "nipple",
  "notebook computer",
  "obelisk",
  "oboe",
  "ocarina",
  "odometer",
  "oil filter",
  "organ",
  "oscilloscope",
  "overskirt",
  "bullock cart",
  "oxygen mask",
  "packet",
  "paddle",
  "paddle wheel",
  "padlock",
  "paintbrush",
  "pajamas",
  "palace",
  "pan flute",
  "paper towel",
  "parachute",
  "parallel bars",
  "park bench",
  "parking meter",
  "passenger car",
  "patio",
  "payphone",
  "pedestal",
  "pencil case",
  "pencil sharpener",
  "perfume",
  "Petri dish",
  "photocopier",
  "plectrum",
  "Pickelhaube",
  "picket fence",
  "pickup truck",
  "pier",
  "piggy bank",
  "pill bottle",
  "pillow",
  "ping-pong ball",
  "pinwheel",
  "pirate ship",
  "pitcher",
  "hand plane",
  "planetarium",
  "plastic bag",
  "plate rack",
  "plow",
  "plunger",
  "Polaroid camera",
  "pole",
  "police van",
  "poncho",
  "billiard table",
  "soda bottle",
  "pot",
  "potter's wheel",
  "power drill",
  "prayer rug",
  "printer",
  "prison",
  "projectile",
  "projector",
  "hockey puck",
  "punching bag",
  "purse",
  "quill",
  "quilt",
  "race car",
  "racket",
  "radiator",
  "radio",
  "radio telescope",
  "rain barrel",
  "recreational vehicle",
  "reel",
  "reflex camera",
  "refrigerator",
  "remote control",
  "restaurant",
  "revolver",
  "rifle",
  "rocking chair",
  "rotisserie",
  "eraser",
  "rugby ball",
  "ruler",
  "running shoe",
  "safe",
  "safety pin",
  "salt shaker",
  "sandal",
  "sarong",
  "saxophone",
  "scabbard",
  "weighing scale",
  "school bus",
  "schooner",
  "scoreboard",
  "CRT screen",
  "screw",
  "screwdriver",
  "seat belt",
  "sewing machine",
  "shield",
  "shoe store",
  "shoji",
  "shopping basket",
  "shopping cart",
  "shovel",
  "shower cap",
  "shower curtain",
  "ski",
  "ski mask",
  "sleeping bag",
  "slide rule",
  "sliding door",
  "slot machine",
  "snorkel",
  "snowmobile",
  "snowplow",
  "soap dispenser",
  "soccer ball",
  "sock",
  "solar thermal collector",
  "sombrero",
  "soup bowl",
  "space bar",
  "space heater",
  "space shuttle",
  "spatula",
  "motorboat",
  "spider web",
  "spindle",
  "sports car",
  "spotlight",
  "stage",
  "steam locomotive",
  "through arch bridge",
  "steel drum",
  "stethoscope",
  "scarf",
  "stone wall",
  "stopwatch",
  "stove",
  "strainer",
  "tram",
  "stretcher",
  "couch",
  "stupa",
  "submarine",
  "suit",
  "sundial",
  "sunglass",
  "sunglasses",
  "sunscreen",
  "suspension bridge",
  "mop",
  "sweatshirt",
  "swimsuit",
  "swing",
  "switch",
  "syringe",
  "table lamp",
  "tank",
  "tape player",
  "teapot",
  "teddy bear",
  "television",
  "tennis ball",
  "thatched roof",
  "front curtain",
  "thimble",
  "threshing machine",
  "throne",
  "tile roof",
  "toaster",
  "tobacco shop",
  "toilet seat",
  "torch",
  "totem pole",
  "tow truck",
  "toy store",
  "tractor",
  "semi-trailer truck",
  "tray",
  "trench coat",
  "tricycle",
  "trimaran",
  "tripod",
  "triumphal arch",
  "trolleybus",
  "trombone",
  "tub",
  "turnstile",
  "typewriter keyboard",
  "umbrella",
  "unicycle",
  "upright piano",
  "vacuum cleaner",
  "vase",
  "vault",
  "velvet",
  "vending machine",
  "vestment",
  "viaduct",
  "violin",
  "volleyball",
  "waffle iron",
  "wall clock",
  "wallet",
  "wardrobe",
  "military aircraft",
  "sink",
  "washing machine",
  "water bottle",
  "water jug",
  "water tower",
  "whiskey jug",
  "whistle",
  "wig",
  "window screen",
  "window shade",
  "Windsor tie",
  "wine bottle",
  "wing",
  "wok",
  "wooden spoon",
  "wool",
  "split-rail fence",
  "shipwreck",
  "yawl",
  "yurt",
  "website",
  "comic book",
  "crossword",
  "traffic sign",
  "traffic light",
  "dust jacket",
  "menu",
  "plate",
  "guacamole",
  "consomme",
  "hot pot",
  "trifle",
  "ice cream",
  "ice pop",
  "baguette",
  "bagel",
  "pretzel",
  "cheeseburger",
  "hot dog",
  "mashed potato",
  "cabbage",
  "broccoli",
  "cauliflower",
  "zucchini",
  "spaghetti squash",
  "acorn squash",
  "butternut squash",
  "cucumber",
  "artichoke",
  "bell pepper",
  "cardoon",
  "mushroom",
  "Granny Smith",
  "strawberry",
  "orange",
  "lemon",
  "fig",
  "pineapple",
  "banana",
  "jackfruit",
  "custard apple",
  "pomegranate",
  "hay",
  "carbonara",
  "chocolate syrup",
  "dough",
  "meatloaf",
  "pizza",
  "pot pie",
  "burrito",
  "red wine",
  "espresso",
  "cup",
  "eggnog",
  "alp",
  "bubble",
  "cliff",
  "coral reef",
  "geyser",
  "lakeshore",
  "promontory",
  "shoal",
  "seashore",
  "valley",
  "volcano",
  "baseball player",
  "bridegroom",
  "scuba diver",
  "rapeseed",
  "daisy",
  "yellow lady's slipper",
  "corn",
  "acorn",
  "rose hip",
  "horse chestnut seed",
  "coral fungus",
  "agaric",
  "gyromitra",
  "stinkhorn mushroom",
  "earth star",
  "hen-of-the-woods",
  "bolete",
  "ear",
  "toilet paper"];
