export const tickCommonNames = [
  "American Dog Tick",
  "Asian Longhorned Tick",
  "Asiatic Cattle Tick",
  "Australian Paralysis Tick",
  "Bighorn Sheep Tick",
  "Blyborough Tick",
  "Bont Ticks",
  "Brown Dog Tick",
  "Brown Ear Tick",
  "Camel Tick",
  "Castor Bean Tick",
  "Cayenne Tick",
  "Dog Ticks",
  "Eastern Black-legged Tick",
  "Fowl Tick",
  "Groundhog Tick",
  "Gulf Coast Tick",
  "Kangaroo Tick",
  "Lone Star Tick",
  "Ornate Cow Tick",
  "Ornate Sheep Tick",
  "Pacific Coast Tick",
  "Pajahuello Tick",
  "Passerine Tick",
  "Pepper Ticks",
  "Pigeon Tick",
  "Rabbit Tick",
  "Rhinoceros Tick",
  "Rocky Mountain Wood Tick",
  "Sand Tampan",
  "Seabird Tick",
  "South African Bont Tick",
  "Southern Reptile Tick",
  "Tasmanian Paralysis Tick",
  "Tortoise Bont Tick",
  "Tortoise Tick",
  "Tropical Bont Tick",
  "Tuatara Tick",
  "Western Black-legged Tick",
  "Western Dog Tick",
  "Winter Tick",
  "Zebra Tick",
  "Bush Tick",
  "Gopher Tortoise Tick",
  "Hedgehog Tick",
  "Long-legged Bat Tick",
  "Red Sheep Tick",
  "Taiga Tick"
];

export const tickScientificNames = [
  "Amblyomma",
  "Amblyomma albolimbatum",
  "Amblyomma americanum",
  "Amblyomma aureolatum",
  "Amblyomma cajennense",
  "Amblyomma coelebs",
  "Amblyomma cohaerens",
  "Amblyomma cordiferum",
  "Amblyomma dissimile",
  "Amblyomma dubitatum",
  "Amblyomma geoemydae",
  "Amblyomma gervaisi",
  "Amblyomma hebraeum",
  "Amblyomma humerale",
  "Amblyomma incisum",
  "Amblyomma integrum",
  "Amblyomma laticaudae",
  "Amblyomma loculosum",
  "Amblyomma longirostre",
  "Amblyomma maculatum",
  "Amblyomma marmoreum",
  "Amblyomma ovale",
  "Amblyomma rotundatum",
  "Amblyomma sabanerae",
  "Amblyomma scalpturatum",
  "Amblyomma splendidum",
  "Amblyomma sylvaticum",
  "Amblyomma testudinarium",
  "Amblyomma tigrinum",
  "Amblyomma triguttatum",
  "Amblyomma tuberculatum",
  "Amblyomma varanense",
  "Amblyomma variegatum",
  "Archaeocroton sphenodonti",
  "Argas persicus",
  "Argas reflexus",
  "Argas vespertilionis",
  "Bothriocroton hydrosauri",
  "Carios kelleyi",
  "Dermacentor",
  "Dermacentor albipictus",
  "Dermacentor andersoni",
  "Dermacentor auratus",
  "Dermacentor compactus",
  "Dermacentor hunteri",
  "Dermacentor marginatus",
  "Dermacentor occidentalis",
  "Dermacentor reticulatus",
  "Dermacentor rhinocerinus",
  "Dermacentor similis",
  "Dermacentor variabilis",
  "Haemaphysalis bancrofti",
  "Haemaphysalis concinna",
  "Haemaphysalis inermis",
  "Haemaphysalis leporispalustris",
  "Haemaphysalis longicornis",
  "Haemaphysalis punctata",
  "Haemaphysalis semermis",
  "Haemaphysalis sulcata",
  "Hyalomma",
  "Hyalomma aegyptium",
  "Hyalomma dromedarii",
  "Hyalomma marginatum",
  "Ixodes",
  "Ixodes acutitarsus",
  "Ixodes cookei",
  "Ixodes cornuatus",
  "Ixodes frontalis",
  "Ixodes hexagonus",
  "Ixodes hirsti",
  "Ixodes holocyclus",
  "Ixodes ovatus",
  "Ixodes pacificus",
  "Ixodes persulcatus",
  "Ixodes pilosus",
  "Ixodes ricinus",
  "Ixodes scapularis",
  "Ixodes uriae",
  "Ixodes vespertilionis",
  "Ornithodoros coriaceus",
  "Ornithodoros savignyi",
  "Rhipicephalus",
  "Rhipicephalus appendiculatus",
  "Rhipicephalus bursa",
  "Rhipicephalus evertsi",
  "Rhipicephalus maculatus",
  "Rhipicephalus microplus",
  "Rhipicephalus pulchellus",
  "Rhipicephalus sanguineus",
  "Robertsicus elaphensis"

];


